const HOURS_PER_WEEK = 40
const WORK_WEEKS_PER_YEAR = 48
const EXPERIENCE_LEVELS = [
    {id: 'entry', title: 'Entry'},
    {id: 'mid', title: 'Mid'},
    {id: 'senior', title: 'Senior'},
    {id: 'staff', title: 'Staff'},
    {id: 'principal', title: 'Principal'}
]
const EXPERIENCE_YEARS = [
    {id: '0', title: 'None'},
    {id: '1', title: '1-2'},
    {id: '2', title: '3-4'},
    {id: '3', title: '5-6'},
    {id: '4', title: '7-8'},
    {id: '5', title: '9-10'},
    {id: '6', title: '11+'},
]

const LANGUAGES = [
    'Javascript',
    'Typescript',
    'Java',
    'Python',
    'C',
    'C++',
    'C#',
    'SQL',
    'PHP',
    'Ruby',
    'Swift',
    'Objective-C',
    'Kotlin',
    'HTML',
    'CSS',
    'Golang',
    'Perl',
    'Rust',
    'R',
    'Matlab'
]

const SKILLS = [
    'React',
    'Node.js',
    'MongoDB',
    'Express.js',
    'Angular',
    'AngularJS',
    'Next.js',
    'Flask',
    'Django',
    'Spring Boot',
    'Svelte',
    'Vue.js',
    'jQuery',
    'Ember.js',
    'Backbone',
    'Semantic-UI',
    'Foundation',
    'Preact',
    'ASP.NET Core',
    'Laravel',
    'Ruby on Rails',
    'Cake PHP',
    'Koa',
    'Phoenix',
    'AWS',
    'Azure',
    'GCP',
    'Firebase',
    'Nest.js',
    'Docker',
    'Kubernetes',
    'iOS',
    'Android',
    '.NET',
    'Maven',
    'JUnit',
    'Jest',
    'React Native',
    'Redux',
    'Redis',
    'Pandas',
    'Hibernate',
    'Selenium',
    'VSCode',
    'REST APIs',
    'CI/CD',
    'GraphQL',
    'PostgreSQL',
]

module.exports = {
    HOURS_PER_WEEK,
    WORK_WEEKS_PER_YEAR,
    EXPERIENCE_LEVELS,
    EXPERIENCE_YEARS,
    SKILLS,
    LANGUAGES
}